version: '3.4'

services:
  postgres:
    container_name: postgres_container
    image: "postgres" 
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: cta_admin
      POSTGRES_PASSWORD: tototatatiti1234
      POSTGRES_DB: CallToArmsDB
    ports:
      - "6543:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
      - ./servers.json:/pgadmin4/servers.json
    restart: unless-stopped

  games.api:
    image: ${DOCKER_REGISTRY-}gamesapi
    build:
      context: .
      dockerfile: Games.API/Dockerfile
    ports: 
      - "5561:80"
    depends_on:
      - postgres
volumes:
  database-data:
  pgadmin: