version: '3.4'

services:
  postgres:
    container_name: postgres_container
    image: "postgres" 
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: cta_admin
      POSTGRES_PASSWORD: tototatatiti1234
      POSTGRES_DB: CallToArmsDB
    ports:
      - "6543:5432"
    restart: unless-stopped
    labels:
      - traefik.enable=false
    networks:
      - web

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
      - ./servers.json:/pgadmin4/servers.json
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.pgadmin.rule=Host("pgadmin.localhost") || PathPrefix("/pgadmin")
    networks:
      - web

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  calltoarms:
    image: ${DOCKER_REGISTRY-}calltoarms
    build:
      context: .
      dockerfile: CallToArms.API/Dockerfile
    ports: 
        - "5560:80"
        - "40560:443"
    depends_on:
      - postgres
    networks:
      - web

  games-api:
    image: ${DOCKER_REGISTRY-}gamesapi
    build:
      context: .
      dockerfile: Games.API/Dockerfile
    ports:
      - "5001:80"
      - "40001:443"
    networks:
      - web
    labels:
      - traefik.http.routers.games-api.rule=Host("games-api.localhost") || Path("/api/games/")
    depends_on:
      - postgres
      - traefik

volumes:
  database-data:
  pgadmin:

networks:
  web:
    external: true